const moment = require('moment')
const { photoResource } = require('../photo')

const full = (property) => {
  return (({
    id,
    authorName,
    title,
    noOfRooms,
    districtId,
    street,
    houseNo,
    aptNo,
    floor,
    autonomousHeat,
    price,
    material,
    floors,
    buildingType,
    squareTotal,
    squareLiving,
    squareKitchen,
    renovated,
    builtAt,
    description,
    type,
    createdAt,
    updatedAt,
    photos,
    author,
    propertyStatus,
    contract,
    motivation,
    source,
    ownerName,
    ownerPhone,
    ownerBirthday,
    isOnViber,
    isOnTelegram,
    isOnFacebook,
    isOnWhatsapp,
    reasonToSell
  }) => ({
    id,
    authorName,
    title,
    noOfRooms,
    districtId,
    street,
    houseNo,
    aptNo,
    floor,
    autonomousHeat,
    price,
    material,
    floors,
    buildingType,
    squareTotal,
    squareLiving,
    squareKitchen,
    renovated,
    builtAt,
    description,
    type,
    createdAt,
    updatedAt,
    author,
    photos: photos.map(p => photoResource.full(p)),
    propertyStatus,
    contract,
    motivation,
    source,
    ownerName,
    ownerPhone,
    ownerBirthday: moment(ownerBirthday).format('DD-MM-YYYY'),
    isOnViber,
    isOnTelegram,
    isOnFacebook,
    isOnWhatsapp,
    reasonToSell
  }))(property)
}

module.exports = { full }
