const moment = require('moment')
const { photoResource } = require('../photo')

const brief = (property) => {
  return (({
    id,
    authorName,
    title,
    districtId,
    street,
    houseNo,
    floor,
    price,
    material,
    floors,
    buildingType,
    squareTotal,
    squareLiving,
    squareKitchen,
    description,
    createdAt,
    updatedAt,
    imageURL,
    propertyStatus,
    contract,
    motivation,
    ownerName,
    ownerPhone
  }) => ({
    id,
    authorName,
    title,
    districtId,
    street,
    houseNo,
    floor,
    price,
    material,
    floors,
    buildingType,
    squareTotal,
    squareLiving,
    squareKitchen,
    description,
    createdAt,
    updatedAt,
    imageURL,
    propertyStatus,
    contract,
    motivation,
    ownerName,
    ownerPhone
  }))(property)
}

const full = (property) => {
  return (({
    id,
    title,
    noOfRooms,
    districtId,
    street,
    houseNo,
    aptNo,
    floor,
    autonomousHeat,
    price,
    material,
    floors,
    buildingType,
    squareTotal,
    squareLiving,
    squareKitchen,
    renovated,
    builtAt,
    description,
    type,
    createdAt,
    updatedAt,
    photos,
    author,
    propertyStatus,
    contract,
    motivation,
    ownerName,
    ownerPhone,
    ownerBirthday
  }) => ({
    id,
    title,
    noOfRooms,
    districtId,
    street,
    houseNo,
    aptNo,
    floor,
    autonomousHeat,
    price,
    material,
    floors,
    buildingType,
    squareTotal,
    squareLiving,
    squareKitchen,
    renovated,
    builtAt,
    description,
    type,
    createdAt,
    updatedAt,
    author,
    photos: photos.map(p => photoResource.brief(p)),
    propertyStatus,
    contract,
    motivation,
    ownerName,
    ownerPhone,
    ownerBirthday: moment(ownerBirthday).format('DD-MM-YYYY')
  }))(property)
}

module.exports = { brief, full }
