const moment = require('moment')
const { photoResource } = require('../photo')

const brief = (house) => {
  return (({
    id,
    authorName,
    title,
    districtId,
    street,
    houseNo,
    price,
    material,
    floors,
    buildingType,
    squareTotal,
    squareLiving,
    squareKitchen,
    squareLand,
    description,
    createdAt,
    updatedAt,
    imageURL,
    propertyStatus,
    contract,
    motivation,
    ownerName,
    ownerPhone
  }) => ({
    id,
    authorName,
    title,
    districtId,
    street,
    houseNo,
    price,
    material,
    floors,
    buildingType,
    squareTotal,
    squareLiving,
    squareKitchen,
    squareLand,
    description,
    createdAt,
    updatedAt,
    imageURL,
    propertyStatus,
    contract,
    motivation,
    ownerName,
    ownerPhone
  }))(house)
}

const full = (house) => {
  return (({
    id,
    title,
    noOfRooms,
    districtId,
    street,
    houseNo,
    price,
    material,
    floors,
    buildingType,
    squareTotal,
    squareLiving,
    squareKitchen,
    squareLand,
    registrationNo,
    renovated,
    garage,
    builtAt,
    description,
    type,
    createdAt,
    updatedAt,
    photos,
    author,
    propertyStatus,
    contract,
    motivation,
    ownerName,
    ownerPhone,
    ownerBirthday,
    isOnViber,
    isOnTelegram,
    isOnFacebook,
    isOnWhatsapp
  }) => ({
    id,
    title,
    noOfRooms,
    districtId,
    street,
    houseNo,
    price,
    material,
    floors,
    buildingType,
    squareTotal,
    squareLiving,
    squareKitchen,
    squareLand,
    registrationNo,
    renovated,
    garage,
    builtAt,
    description,
    type,
    createdAt,
    updatedAt,
    author,
    photos: photos.map(p => photoResource.brief(p)),
    propertyStatus,
    contract,
    motivation,
    ownerName,
    ownerPhone,
    ownerBirthday: moment(ownerBirthday).format('DD-MM-YYYY'),
    isOnViber,
    isOnTelegram,
    isOnFacebook,
    isOnWhatsapp
  }))(house)
}

module.exports = { brief, full }
