const express = require('express')
const appRouter = express.Router()
const indexRouter = require('../components/index/router')
const { authRouter } = require('../components/auth')
const { userRouter } = require('../components/user')
const { houseRouter } = require('../components/house')
const { apartmentRouter } = require('../components/apartment')
const { commerceRouter } = require('../components/commerce')
const { apartmentBuyerRouter } = require('../components/apartmentBuyer')
const { houseBuyerRouter } = require('../components/houseBuyer')
const { commerceBuyerRouter } = require('../components/commerceBuyer')
const { constantsRouter } = require('../components/constants')
const { archiveRouter } = require('../components/archive')

appRouter.use('/', indexRouter)
appRouter.use('/auth', authRouter)
appRouter.use('/users', userRouter)
appRouter.use('/houses', houseRouter)
appRouter.use('/apartments', apartmentRouter)
appRouter.use('/commerce', commerceRouter)
appRouter.use('/buyers/apartments', apartmentBuyerRouter)
appRouter.use('/buyers/houses', houseBuyerRouter)
appRouter.use('/buyers/commerce', commerceBuyerRouter)
appRouter.use('/constants', constantsRouter)
appRouter.use('/archive', archiveRouter)

module.exports = appRouter
