const moment = require('moment')
const { photoResource } = require('../photo')

const full = (commerce) => {
  return (({
    id,
    title,
    responsibleID,
    propertyStatus,
    contract,
    motivation,
    source,
    noOfRooms,
    districtId,
    street,
    houseNo,
    price,
    floor,
    floors,
    buildingType,
    squareTotal,
    squareLiving,
    renovated,
    autonomousHeat,
    description,
    ownerName,
    ownerPhone,
    isOnViber,
    isOnTelegram,
    isOnFacebook,
    isOnWhatsapp,
    reasonToSell,
    createdAt,
    updatedAt,
    authorName,
    photos,
    ownerBirthday
  }) => ({
    id,
    title,
    responsibleID,
    propertyStatus,
    contract,
    motivation,
    source,
    noOfRooms,
    districtId,
    street,
    houseNo,
    price,
    floor,
    floors,
    buildingType,
    squareTotal,
    squareLiving,
    renovated,
    autonomousHeat,
    description,
    ownerName,
    ownerPhone,
    isOnViber,
    isOnTelegram,
    isOnFacebook,
    isOnWhatsapp,
    reasonToSell,
    createdAt,
    updatedAt,
    authorName,
    photos: photos.map(p => photoResource.full(p)),
    ownerBirthday: moment(ownerBirthday).format('DD-MM-YYYY')
  }))(commerce)
}

module.exports = { full }
